-- Non-echoed input for obtaining passwords
-- Works with GNAT/Linux and Windows and ObjectAda/Windows
-- Copyright (C) 2022 by PragmAda Software Engineering
--
-- History:
-- 2022 Feb 15     J. Carter          V1.3--OA 10.3 does not need a workaround
-- 2021 May 15     J. Carter          V1.2--Mention OA workaround
-- 2021 Feb 01     J. Carter          V1.1--Revised comments about what works
-- 2017 Feb 01     J. Carter          V1.0--Initial release
--
function Password_Line (Echo : Boolean := True) return String;
-- Gets a line from standard input, skips the line terminator, and returns the line
-- If Echo, characters are echoed as '*'; otherwise, characters are not echoed
-- Backspace and Enter are the only control keys recognized and handled
--
-- SPDX-License-Identifier: GPL-2.0-or-later WITH GNAT-exception
-- See https://spdx.org/licenses/
-- If you find this software useful, please let me know, either through
-- github.com/jrcarter or directly to pragmada@pragmada.x10hosting.com
