-- Non-echoed input for obtaining passwords
-- Works with GNAT/Linux and Windows and ObjectAda/Windows
-- Copyright (C) 2022 by PragmAda Software Engineering
--
-- History:
-- 2022 Feb 15     J. Carter          V1.3--OA 10.3 does not need a workaround
-- 2021 May 15     J. Carter          V1.2--Mention OA workaround
-- 2021 Feb 01     J. Carter          V1.1--Revised comments about what works
-- 2017 Feb 01     J. Carter          V1.0--Initial release
--
function Password_Line (Echo : Boolean := True) return String;
-- Gets a line from standard input, skips the line terminator, and returns the line
-- If Echo, characters are echoed as '*'; otherwise, characters are not echoed
-- Backspace and Enter are the only control keys recognized and handled
--
-- This is free software; you can redistribute it and/or modify it under
-- terms of the GNU General Public License as published by the Free Software
-- Foundation; either version 2, or (at your option) any later version.
-- This software is distributed in the hope that it will be useful, but WITH
-- OUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
-- or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
-- for more details. Free Software Foundation, 59 Temple Place - Suite
-- 330, Boston, MA 02111-1307, USA.
--
-- As a special exception, if other files instantiate generics from this
-- unit, or you link this unit with other files to produce an executable,
-- this unit does not by itself cause the resulting executable to be
-- covered by the GNU General Public License. This exception does not
-- however invalidate any other reasons why the executable file might be
-- covered by the GNU Public License.
